// ReportResults.jsx – Displays stats, AI narrative, and PDF download
import React from 'react'
import StatCard from './StatCard'

const STAT_CONFIG = [
  { key: 'median_price',       label: 'Median Sale Price',    icon: '🏠', accent: '#2563EB' },
  { key: 'days_on_market',     label: 'Median Days on Market',icon: '📅', accent: '#0ea5e9' },
  { key: 'new_listings',       label: 'New Listings',         icon: '📋', accent: '#8b5cf6' },
  { key: 'active_listings',    label: 'Active Listings',      icon: '🏘️',  accent: '#f59e0b' },
  { key: 'price_growth',       label: 'Price Growth (YOY)',   icon: '📈', accent: '#10b981' },
  { key: 'homes_sold',         label: 'Homes Sold',           icon: '🔑', accent: '#ef4444' },
]

/**
 * Format a raw number or string as a display value.
 * Handles dollar amounts, percentages, and plain numbers.
 */
function formatValue(key, raw) {
  if (raw === undefined || raw === null) return '—'
  if (typeof raw === 'string') return raw  // Already formatted by backend

  switch (key) {
    case 'median_price':
      return `$${Number(raw).toLocaleString()}`
    case 'price_growth':
    case 'homes_sold_yoy':
      return `${raw > 0 ? '+' : ''}${Number(raw).toFixed(1)}%`
    case 'days_on_market':
      return `${raw} days`
    default:
      return Number(raw).toLocaleString()
  }
}

export default function ReportResults({ data, agentName, zipCode, pdfUrl }) {
  const { market_data, summary } = data
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  })

  // Build download URL pointing to FastAPI static file server
  const downloadUrl = `http://localhost:8000${pdfUrl}`

  return (
    <div className="results-section" id="results-section">
      <div className="results-header">
        <div>
          <h2 className="results-title">Market Report — {zipCode}</h2>
          <p className="results-meta">Generated for {agentName} · {now} · Powered by Redfin Data + Groq AI</p>
        </div>
      </div>

      {/* Data Source Banner */}
      <div className="data-source-banner">
        <span>📊</span>
        <span>
          National baseline from <strong>Redfin Housing Market Data</strong> (Apr 2026) with local variance applied for {zipCode}
        </span>
      </div>

      {/* Stats Grid */}
      <div className="stats-grid">
        {STAT_CONFIG.map(({ key, label, icon, accent }) => {
          const raw = market_data[key]
          const yoyKey = `${key}_yoy`
          const yoyRaw = market_data[yoyKey]
          const yoyStr = yoyRaw !== undefined && yoyRaw !== null
            ? `${Number(yoyRaw) >= 0 ? '+' : ''}${Number(yoyRaw).toFixed(2)}%`
            : null

          return (
            <StatCard
              key={key}
              icon={icon}
              label={label}
              value={formatValue(key, raw)}
              change={yoyStr}
              accentColor={accent}
            />
          )
        })}
      </div>

      {/* AI Narrative */}
      <div className="narrative-card">
        <div className="narrative-header">
          <div className="narrative-icon">🤖</div>
          <div>
            <div className="narrative-title">AI Market Analysis</div>
            <div className="narrative-subtitle">Generated by Groq · llama-3.3-70b-versatile</div>
          </div>
        </div>
        <div className="narrative-body">{summary}</div>
      </div>

      {/* Download CTA */}
      <div className="download-card">
        <div className="download-info">
          <h3>📄 Your Branded PDF Report is Ready</h3>
          <p>Professional report with SnapReport + Snaphomz branding · Includes all market data + AI narrative</p>
        </div>
        <a
          id="pdf-download-btn"
          className="btn-download"
          href={downloadUrl}
          download
          target="_blank"
          rel="noopener noreferrer"
        >
          ⬇ Download PDF Report
        </a>
      </div>
    </div>
  )
}
